### ISSUE TITLE
Failed to install from github sources

### ISSUE THREAD

**Issue by ProLoDs** [netzob/netzob#118]
Python version:
3.6.2

Commands: 
```
git checkout [netzob-url]
sudo python3 setup.py install
netzob
```
Error msg:
```
Traceback (most recent call last):
  File "/usr/bin/netzob", line 4, in <module>
    __import__('pkg_resources').run_script('Netzob==1.0.2', 'netzob')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 741, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'netzob'
```

The pip version works.
Greetings

**Comment by msgpeek** [comment]
Can't reproduce. No obvious idea. How did you install the dependencies? 

Python3.6.2 sounds like Archlinux. If it is, there's an AUR-package for netzob. But it just runs setyp.py...

**Comment by ProLoDs** [comment]
Hi,
I run Fedora. I installed the dependencies with 
```
sudo pip3 install r- requirements.txt 
```

**Comment by Sygus** [comment]
latest version (2.0.0) should work
