### ISSUE TITLE
The documentation builder (sphinx) shows import errors 

### ISSUE THREAD

**Issue by gbossert** [netzob/netzob#15]
When triggering the documentation build with the command:: 
```
python setup.py build_sphinx
```
some import errors are reported such as
```
netzob/doc/documentation/source/developer_guide/API/netzob.Inference.Grammar.rst:53: WARNING: autodoc: failed to import module u'netzob.Inference.Grammar.LearningAlgorithm'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "src/netzob/Inference/Grammar/LearningAlgorithm.py", line 44, in <module>
    from netzob.Inference.Grammar.Oracles.NetworkOracle import NetworkOracle
  File "src/netzob/Inference/Grammar/Oracles/NetworkOracle.py", line 44, in <module>
    from netzob.Common.MMSTD.Dictionary.AbstractionLayer import AbstractionLayer
ImportError: No module named MMSTD.Dictionary.AbstractionLayer
```
I believe these errors are due to old netzob code hidding in some dark places of the repository.

**Comment by gbossert** [comment]
Invalid imports were removed.
