### ISSUE TITLE
StopIteration() exception

### ISSUE THREAD

**Issue by rnatella** [netzob/netzob#164]
I am playing with the tutorial, and the following exception occurs:

----------------

Traceback (most recent call last):
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Model/Vocabulary/Domain/Parser/MessageParser.py", line 293, in _parseBitArrayWithField
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "netzob_demo.py", line 31, in <module>
    print(symbol)
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Model/Vocabulary/AbstractField.py", line 702, in __str__
    result = self.getCells(encoded=True)
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Common/Utils/Decorators.py", line 188, in wrapped_f
    return func(*args, **kwargs)
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Model/Vocabulary/AbstractField.py", line 281, in getCells
    return DataAlignment.align(data, self, encoded=encoded)
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Common/Utils/Decorators.py", line 188, in wrapped_f
    return func(*args, **kwargs)
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Common/Utils/DataAlignment/DataAlignment.py", line 260, in align
    return dAlignment.execute()
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Common/Utils/DataAlignment/DataAlignment.py", line 163, in execute
    alignedMsg = next(mp.parseRaw(d, targetedFieldLeafFields))
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Model/Vocabulary/Domain/Parser/MessageParser.py", line 229, in parseBitarray
    for parsingResult in parsingResults:
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Model/Vocabulary/Domain/Parser/MessageParser.py", line 281, in _parseBitArrayWithField
    for x in generator:
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Model/Vocabulary/Domain/Parser/MessageParser.py", line 281, in _parseBitArrayWithField
    for x in generator:
  File "/home/user/netzob/netzob-master/netzob/src/netzob/Model/Vocabulary/Domain/Parser/MessageParser.py", line 281, in _parseBitArrayWithField
    for x in generator:
  [Previous line repeated 1 more time]
RuntimeError: generator raised StopIteration

----------------

Commenting out the line "raise StopIteration()" at the end of "src/netzob/Model/Vocabulary/Domain/Parser/MessageParser.py", and raising instead "InvalidParsingPathException" seems to solve the issue.

**Comment by skleber** [comment]
The reason for this is, that Python 3.5 changed the way how generators ought to use StopIteration:
https://www.python.org/dev/peps/pep-0479/

I wonder, if it would not even be more straightforward to simply return like the PEP suggests on an exhausted generator instead of raising some kind of exception.

**Comment by Sygus** [comment]
Thanks for the associated PR. Merged!
