### ISSUE TITLE
Netzob crashes while importing PCAP files

### ISSUE THREAD

**Issue by GauthamGoli** [netzob/netzob#27]
I tried to import a PCAP file of size 8 mb while following the tutorial on the main website. Netzob has crashed multiple times. The following is the traceback for that exception. Not being able to import PCAPs is a huge inconvenience. 
`DEBUG:root:  Local configuration file used: /root/.netzob
DEBUG:root:  Workspace path declared in configuration file: /root/workspace/netzob
DEBUG:root:  Workspace R/W access is valid: /root/workspace/netzob
DEBUG:root:+ Load workspace...
DEBUG:root:  Workspace configuration file found: /root/workspace/netzob/workspace.xml
DEBUG:root:  Workspace configuration file /root/workspace/netzob/workspace.xml is valid against XSD scheme /usr/share/netzob/xsds/0.1/Workspace.xsd
DEBUG:root:Bug reporter disabled.
DEBUG:root:Logging config file: /root/workspace/netzob/logging/logging.conf
[MainThread]2016-03-21 09:52:00,756 - NetzobMainController - INFO - Starting netzob UI
[MainThread]2016-03-21 09:52:22,745 - Project - INFO - Save the config file of project monday 21st in /root/workspace/netzob/projects/751429ce-fa7e-4403-93ef-f96322ed7cc1/config.xml
[MainThread]2016-03-21 09:52:22,746 - Project - INFO - Creation of the directory: /root/workspace/netzob/projects/751429ce-fa7e-4403-93ef-f96322ed7cc1
[MainThread]2016-03-21 09:52:22,746 - Workspace - INFO - Save the config file of the workspace New Workspace in /root/workspace/netzob/workspace.xml
[MainThread]2016-03-21 09:52:23,432 - Project - INFO - Loading project 'monday 21st' from workspace.

(netzob:3361): Gtk-WARNING **: Content added to the action area of a dialog using header bars

(netzob:3361): Gtk-WARNING **: Content added to the action area of a dialog using header bars
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[MainThread]2016-03-21 09:52:37,057 - PCAPImporter - INFO - Starting import from /root/Desktop/captures/3tickets.pcap (linktype:/root/Desktop/captures/3tickets.pcap)
[MainThread]2016-03-21 09:52:37,255 - PCAPImporter - WARNING - Cannot import one of the provided packets since its layer 3 is unsupported (Only IP is currently supported, packet ethernet type = 2054)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[MainThread]2016-03-21 09:52:44,969 - Workspace - INFO - Save the config file of the workspace New Workspace in /root/workspace/netzob/workspace.xml
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/netzob/UI/Vocabulary/Controllers/VocabularyController.py", line 261, in symbolListTreeViewSelection_changed_cb
    self._view.updateSymbolProperties()
  File "/usr/lib/python2.7/dist-packages/netzob/UI/Vocabulary/Views/VocabularyView.py", line 623, in updateSymbolProperties
    self.updateSymbolVariableDefinition()
  File "/usr/lib/python2.7/dist-packages/netzob/UI/Vocabulary/Views/VocabularyView.py", line 629, in updateSymbolVariableDefinition
    variableDisplayerController.run(self.messagesDistributionSymbolViewport)
  File "/usr/lib/python2.7/dist-packages/netzob/UI/Vocabulary/Controllers/VariableDisplayerController.py", line 72, in run
    self._view.run(panel)
  File "/usr/lib/python2.7/dist-packages/netzob/UI/Vocabulary/Views/VariableDisplayerView.py", line 81, in run
    xdotWidget.drawDotCode('\n'.join(dotCode))
  File "/usr/lib/python2.7/dist-packages/netzob/Simulator/XDotWidget.py", line 64, in drawDotCode
    self.set_dotcode(dotCode)
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 1475, in set_dotcode
    self.set_xdotcode(xdotcode)
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 1490, in set_xdotcode
    self.graph = parser.parse()
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 1169, in parse
    DotParser.parse(self)
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 979, in parse
    self.parse_graph()
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 988, in parse_graph
    self.parse_stmt()
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 1018, in parse_stmt
    self.parse_subgraph()
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 1001, in parse_subgraph
    self.parse_stmt()
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 1034, in parse_stmt
    self.handle_node(id, attrs)
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 1144, in handle_node
    shapes.extend(parser.parse())
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 609, in parse
    w = s.read_number()
  File "/usr/lib/python2.7/dist-packages/netzob/ExternalLibs/xdot.py", line 496, in read_number
    return int(self.read_code())
ValueError: invalid literal for int() with base 10: '136.48'

(netzob:3361): Gdk-ERROR **: The program 'netzob' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 26600 error_code 11 request_code 130 (MIT-SHM) minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap`

**Comment by gbossert** [comment]
Can you provide the PCAP you used so that we can check if this issue applies on the latest version of Netzob ?

**Comment by GauthamGoli** [comment]
In the latest command line version, it works fine. But not in the GUI version of netzob.

**Comment by Sygus** [comment]
As the GUI version of Netzob is obsolete, I close this bug.
